version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - currency-compose-network

  naming-server:
    image: drmodi/netflix-eureka-naming-server:0.0.1-SNAPSHOT-DCR
    ports:
      - "8761:8761"
    restart: always
    networks:
      - currency-compose-network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - currency-compose-network

  zuul-api-gateway:
    image: drmodi/netflix-zuul-api-gateway-server:0.0.1-SNAPSHOT-DCR
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-exchange-service:
    image: drmodi/currency-exchange-service:0.0.1-SNAPSHOT-DCR
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:  # Comment ports and next line mapping, boz it will not scale, first service is using 8000 port, will not allow 2 instance to run using same port. After comment it will use the gateway
      - "8000:8000"
    restart: always
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-conversion-service:
    image: drmodi/currency-conversion-service:0.0.1-SNAPSHOT-DCR
    ports:
      - "8100:8100"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
#      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000 # not needed once naming server, apigateway, ribbon started being used
    depends_on:
      - currency-exchange-service
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network


networks:
  currency-compose-network:
